## Author

- **Name:** Yijun Wang 
- **Email:** yijun4@illinois.edu  

## Purpose

This shinyapp utilize Spotify API to demonstrate musical features of author's favorite band and individual - Arctic Monkeys, Nirvana, and Avicii. There are 6 music features selected to represent the music quality of the song: danceability, energy, speechiness, acousticness, liveness, and valence. Additionally, a scatter plot is included for the purpose of studying the relationships between the musical features, accompanied with a fitted linear regression line. The data table is adjustable to the selected artist and include search feature so the user can search a specific song they like. 

## Data

The Data is retrieved from the Spotify API, which original includes 39 columns that describe the author, song, album, link and music features. This application selected 8 of the columns that related with the music features of the song. Based on author's favorite bands and individual, All songs from Nirvana, Arctic Monkeys and Avicii are retrieved using the API. The pre_processed data contains 8 columns and 500 rows. The following are description of music features that are referenced from the Spotify developer website:

Danceability: Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable.

Energy: Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy.

Acousticness: A measure from 0.0 to 1.0 of whether the track is acoustic.

Speechiness: Speechiness detects the presence of spoken words in a track. The more exclusively speech-like the recording (e.g. talk show, audio book, poetry), the closer to 1.0 the attribute value.

Liveness: Detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live.

Valence: A measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).

## References

For Spotify API information, See https://developer.spotify.com/documentation/web-api/

Appentix Reference: https://developer.spotify.com/discover/

More about Arctic Monkeys: https://arcticmonkeys.com/